### ISSUE TITLE
Move readme to doc site

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-monitoring#16]
we should remove [readme in the `8114_metrics_mvp` branch](https://github.com/medic/cht-monitoring/blob/8114_metrics_mvp/README.md) and put all that content on the [public monitoring and alerting page](https://docs.communityhealthtoolkit.org/apps/guides/hosting/monitoring/).

**Comment by mrjones-plip** [comment]
@jkuester - In addition to the move above, what do you think about renaming [the "testing" folder](https://github.com/medic/cht-monitoring/tree/8114_metrics_mvp/tests) to "development"?

My thinking is we can then update the `./development/readme.md` to have information about how to do development and releases.  We can update the newly emptied `./readme.md` to have a link to the docs site for how to use and the local development folder for how to develop.

**Comment by mrjones-plip** [comment]
We should wait until #13 is merged as there's a lot of updates to the main `readme` in it

**Comment by jkuester** [comment]
> renaming [the "testing" folder to "development"

@mrjones-plip Yes, I like it!

**Comment by jkuester** [comment]
@mrjones-plip can this issue be closed now?

**Comment by mrjones-plip** [comment]
yes - thank you sir!
