### ISSUE TITLE
Discussion: branches as main release vehicle

### ISSUE THREAD

**Issue by jkuester** [medic/cht-monitoring#27]
Now that we have cut a few releases with the new process, I wanted to re-visit our strategy here to add some additional pros/cons to the previous discussion.  

Currently, our [release process](https://github.com/medic/cht-monitoring/tree/main/development#developing) involves creating a new branch for every release (every commit to `main`) and then instructing consumers to checkout particular branches locally to get the changes from the release. Tags are also created as part of the process, but are not used.

## Pain points

1. Does not conform to (my understanding) of the git paradigm for branches/tags. Typically when interacting with a git repo, you would view tags as pointer to a fixed commit that will never change and branches, on the other hand, refer to a stream of changes that may include additions in the future.  Treating branches as release pointers will be surprising behavior for anyone with git experience.
2. Does not work well with tooling. GitHub releases assumes that every release is associated with a tag.  If you look at the [release page](https://github.com/medic/cht-monitoring/releases/tag/1.1.0) for a release, you will see info about the tag and commit hash, but not the branch.  Additionally, tools we may want to use in the future, like `semantic-release`, are going to be more difficult to script/configure to operate within a non-standard paradigm
3. "Fix" releases end up with non-standard (in semantic versioning terms) branch names like `1.1.1.x` with the extra `.x` on the end.  I am afraid this will just cause confusion for folks that are familiar with semantic versioning.  

## Proposal

I think we should stick with the same branching pattern as cht-core and just create branches for the major and minor releases.  Fix commits should be just added to the latest existing branch release (e.g. `1.1.x` currently) and should not have a _new_ branch associated with them.  Our deployment documentation can then be updated to note that checking out a new cht-monitoring branch is how to _get new features_, but just doing a `git pull` from the checked out branch is how to get bug fixes.  This will go a long way towards resolving `#1` and `#3`!

Additionally, I know that the main reason we decided to recommend admins checkout branches instead of tags is to avoid the `detached HEAD` warning.  A different way to avoid the warning would be to just recommend checking out tags with the `advice.detachedHead=false` flag set. E.g: `git -c advice.detachedHead=false checkout 1.1.0`.  This will suppress the warning that is typically displayed in the terminal.  This approach would mean that consumers could just target the tags directly (and we would not have to document the separate `git pull` process mentioned above for fixes).  

Anyway, these are just my thoughts. Hoping for an open and productive discussion here!  @mrjones-plip @m5r @eljhkrr

**Comment by mrjones-plip** [comment]
Thanks for the setup and background on the topic @jkuester ! 

Reading over your pain points and proposal, I don't feel that strongly about the topic. As such, I'm OK with your `advice.detachedHead` work around.

It would be great if we could automate the process - possibly with [this GH Action](https://github.com/K-Phoen/semver-release-action)?

**Comment by m5r** [comment]
I completely agree that using branches as release pointers is counter-intuitive for all the reasons you mentioned.  
Plus, I didn't get *why* we had an extra digit for patch releases so I'm all for following a more standard approach.
